# Generated by Django 5.2.13 on 2026-04-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
